In [1]:
import numpy as np
import pandas as pd

In [8]:
#combine NIKI 

nilist = pd.read_csv('NKI_list.txt')
nkipet = pd.read_csv('scripts/nkidata/NKI_cbfpetcorr.csv')
nkipetroi = pd.read_csv('scripts/nkidata/NKI_cbfpetroicorr.csv')
nilist.shape,nkipet.shape

((1566, 2), (1566, 5))

In [9]:
nilist.join(nkipet)

            sub   ses      SCBF     BASIL     SCRUB     PVCGM     PVCWM
0     A00034350   TRT  0.290407  0.322347  0.273611  0.304865  0.318857
1     A00034350  FLU1  0.290463  0.339033  0.286468  0.443945  0.152672
2     A00063003   TRT  0.043844  0.154278  0.223665  0.238226  0.007140
3     A00063003  BAS1  0.242988  0.286146  0.220336  0.453398  0.072208
4     A00063003  FLU1 -0.073996 -0.036646 -0.058908  0.076296 -0.179290
...         ...   ...       ...       ...       ...       ...       ...
1561  A00065975  BAS1  0.000000  0.000000  0.000000  0.000000  0.000000
1562  A00065975  FLU2  0.000000  0.000000  0.000000  0.000000  0.000000
1563  A00065975  FLU1  0.000000  0.000000  0.000000  0.000000  0.000000
1564  A00058516  BAS1  0.000000  0.000000  0.000000  0.000000  0.000000
1565  A00061727  BAS1  0.000000  0.000000  0.000000  0.000000  0.000000

[1566 rows x 7 columns]

In [42]:
nilist = pd.read_csv('NKI_list.txt')
nkipet = pd.read_csv('scripts/nkidata/NKI_cbfpetcorr.csv')
nk = nilist.join(nkipet)
nk3 = pd.read_csv('scripts/nkidata/NKI_participants_New.tsv',sep='\t')
nk = pd.merge(nk,nk3,on=["sub","ses"])

pn1 = pd.read_csv('scripts/pncdata/PNC_cbfpetcorr.csv')
pn1= pn1.drop_duplicates()
pn2 = pd.read_csv('scripts/pncdata/pnc_demographic.csv')
pn2 = pn2.drop_duplicates()
pn = pd.merge(pn1,pn2,on="sub")

gr1=pd.read_csv('scripts/grympydata/demographics.csv')
gr2 =pd.read_csv('scripts/grympydata/IRR_cbfpetcorr.csv')
gr = pd.merge(gr1,gr2,on="sub")



ags1 =pd.read_excel('scripts/ageingdata//Book1.xlsx',engine='openpyxl')
ags2 =pd.read_csv('scripts/ageingdata/AGE_cbfpetcorr.csv')
ag = pd.merge(ags1,ags2,on='sub')

cd1 = pd.read_excel('scripts/ftddata/Updated_LEFFTDS.xlsx',engine='openpyxl')
cd2 = pd.read_csv('scripts/ftddata/FTD_cbfpetcorr.csv')
cd = pd.merge(cd1,cd2,on='sub')

In [59]:
# combine all the data and label with common names 
agdata = pd.DataFrame({'sub':ag['sub'],'Datasets': np.repeat('AGE',len(ag)),'SCBF': ag['SCBF'],'AGE':ag['age'],
                       'BASIL': ag['BASIL'],'SCRUB': ag['SCRUB'],'PVCGM': ag['PVCGM'],'PVCWM': ag['PVCWM']})


grdata  = pd.DataFrame({'sub':gr['sub'],'Datasets': np.repeat('IRR',len(gr)),'SCBF': gr['SCBF'],'AGE':gr['age'],'BASIL': gr['BASIL'],
                       'SCRUB': gr['SCRUB'],'PVCGM': gr['PVCGM'],'PVCWM': gr['PVCWM']})

cddata = pd.DataFrame({'sub':cd['sub'],'Datasets': np.repeat('FTD',len(cd)),'SCBF': cd['SCBF'],'AGE':cd['age'],'BASIL': cd['BASIL']
                        ,'PVCGM': cd['PVCGM'],'PVCWM': cd['PVCWM']})



pndata  = pd.DataFrame({'sub':pn['sub'],'Datasets': np.repeat('PNC',len(pn)),'SCBF': pn['SCBF'],'AGE':pn['age'],
                       'BASIL': pn['BASIL'],'SCRUB': pn['SCRUB'],'PVCGM': pn['PVCGM'],'PVCWM': pn['PVCWM'], })



nkdata1 = pd.DataFrame({'sub':nk['sub']+nk['ses'],'Datasets': np.repeat('NKI',len(nk)),'SCBF': nk['SCBF'],'AGE': nk['age'],'BASIL': nk['BASIL'],
                   'SCRUB': nk['SCRUB'],'PVCGM': nk['PVCGM'],'PVCWM': nk['PVCWM']   })

gmdata = pd.concat([pndata,nkdata,grdata,cddata,agdata])

In [61]:
gmdata.to_csv('petcbfcorr.csv',index=False,sep=',')

297.8