In [1]:
import pandas as pd

In [2]:
demo  = pd.read_csv('scripts/pncdata/n1601_demographics_go1_20161212.csv')
oldpncs = pd.read_csv('scripts/pncdata/smoothingfhwmoldpn.csv')
qc = pd.read_csv('scripts/pncdata/pnc_allsubjects_qc.csv')
den = demo.merge(oldpncs, on = 'scanid')
dd = pd.read_csv('scripts/pncdata/bblid_renamed.csv')
den= den.merge(dd, on ='bblid')

d2 = pd.read_csv('scripts/pncdata/smoothingfhwm.csv')
den= den.merge(d2, on ='sub')
den = den.drop_duplicates()
den = den.dropna()
den = den.merge(qc,on='sub')

den

,bblid,scanid,sex,race,race2,ethnicity,ageAtClinicalAssess1,ageAtCnb1,ageAtScan1,edu1,...,basilQEI,pvcQEI,GMmeanCBF,WMmeanCBF,Gm_Wm_CBF_ratio,NEG_CBF_PERC,NEG_SCORE_PERC,NEG_SCRUB_PERC,NEG_BASIL_PERC,NEG_PVC_PERC
0,80010,2894,1,1,1,2,260,260,261,14,...,0.829763,0.822522,57.499694,32.759455,1.755209,4.020668,3.521796,2.072693,0.0,0.0
1,80208,3016,1,2,2,2,245,245,246,11,...,0.836807,0.841522,62.164782,34.006964,1.828002,2.770139,2.783554,1.368301,0.0,0.0
2,80249,2648,2,1,1,2,250,250,250,16,...,0.813198,0.821055,45.710066,21.706320,2.105841,5.391176,5.080552,2.616616,0.0,0.0
3,80265,3145,2,2,2,2,245,245,246,12,...,0.812693,0.816000,93.406753,45.305851,2.061693,1.583403,1.725587,0.232663,0.0,0.0
4,80289,2794,1,2,2,2,241,241,241,11,...,0.792492,0.782026,48.666391,27.897198,1.744490,6.515539,6.566728,2.691042,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,133228,6354,2,1,1,2,122,122,123,3,...,0.851479,0.842495,69.271947,30.918111,2.240497,1.711915,1.853700,0.294071,0.0,0.0
1528,133242,6416,2,1,1,2,186,186,187,9,...,0.828039,0.826092,68.296337,32.111061,2.126879,3.685445,3.721517,1.809656,0.0,0.0
1529,136004,8091,2,2,2,2,180,180,187,8,...,0.822361,0.812215,82.499233,42.836403,1.925914,2.137825,2.823890,1.078101,0.0,0.0
1530,139469,8450,2,2,2,2,106,106,107,2,...,0.816862,0.814098,94.183105,50.122332,1.879065,2.649119,3.146182,0.819024,0.0,0.0
1531,139532,8364,1,2,2,2,116,116,117,3,...,0.752402,0.757675,89.786423,59.527295,1.508324,2.542470,1.922635,0.533747,0.0,0.0

In [3]:
datax = den[['bblid','scanid','sex','age','oldCBF','CBF','SCRUB','BASIL','PVGM','PVWM']]
datax = datax.drop_duplicates()
datax = datax.dropna()
datax

,bblid,scanid,sex,age,oldCBF,CBF,SCRUB,BASIL,PVGM,PVWM
0,80010,2894,1,21.750000,4.898947,4.390647,4.129930,5.759419,6.266686,7.218260
1,80208,3016,1,20.500000,6.103240,4.233402,4.133365,6.487819,6.385266,7.746638
2,80249,2648,2,20.833333,5.077679,3.982382,3.792772,5.357282,5.635230,8.178168
3,80265,3145,2,20.500000,6.935492,4.548486,4.587238,5.470947,5.384929,8.445960
4,80289,2794,1,20.083333,5.851090,4.193362,4.088218,5.674073,5.733611,6.825908
...,...,...,...,...,...,...,...,...,...,...
1526,133228,6354,2,10.250000,6.819508,4.442970,4.376254,5.887147,6.248949,7.307079
1528,133242,6416,2,15.583333,6.480385,4.085942,4.191093,5.562529,6.004368,7.542295
1529,136004,8091,2,15.583333,7.664898,4.875016,4.802158,6.192768,6.163597,7.173835
1530,139469,8450,2,8.916667,7.026221,4.495429,4.483714,5.836429,6.252064,7.554225
1531,139532,8364,1,9.750000,8.234836,4.407330,4.617600,6.307792,5.493670,6.874225

In [ ]:
agdata3 = pd.DataFrame({'Datasets': np.repeat('AGE',len(ag)),'CBF GM': ag['SCRUB_GM'], 'CBF WM': ag['SCRUB_WM'],'CBF TYPE':'SCRUB','QEI': ag['scrubQEI'],
                       'NEG_CBF':ag["NEG_SCRUB_PERC"],'FD':ag['FD'],'AGE':ag['age'],'CBF_R':ag['SCRUB_GM']/ag['SCRUB_WM']})